version: "3.4"

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/nginx/etc/default.conf:/etc/nginx/conf.d/default.conf"
      - "./src/:/var/www/html"
  php:
    image: php:7.2-fpm-alpine
    volumes:
      - "./src/:/var/www/html"
  mysql:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
    ports:
      - "3306:3306"